/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DBConnector;

import com.automo.ClaimFrame;
import com.automo.CustomerFrame;
import com.automo.dao.ClaimDao;
import com.automo.dao.CustomerDao;
import com.automo.entity.Claim;
import com.automo.entity.Contact;
import com.automo.entity.Customer;
import com.automo.entity.Vehicle;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 */
public class MasterFrame extends javax.swing.JFrame {

    private static final MasterFrame instance = new MasterFrame();
    ClaimDao claimDao;
    CustomerDao customerDao;
    public static MasterFrame getInstance() {
        return instance;
    }
    /**
     * Creates new form MasterFrame
     */
    private MasterFrame() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
//            UIManager.setLookAndFeel( "com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MasterFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        claimDao = new ClaimDao();
        customerDao = new CustomerDao();
        claimFrame = new ClaimFrame();
        customerFrame = new CustomerFrame();
        setTitle("MasterFrame");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        claimFrameButton = new java.awt.Button();
        customerNameBox = new javax.swing.JTextField();
        vehicleYearBox = new javax.swing.JTextField();
        vehicleMakeBox = new javax.swing.JTextField();
        vehicleModelBox = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        editVehicleButton = new java.awt.Button();
        customerNameBox2 = new javax.swing.JTextField();
        button2 = new java.awt.Button();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        windowMenu = new javax.swing.JMenu();
        customerFrameMenuItem = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel5.setText("Vehicle Make");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel4.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Customer Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel4.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Vehicle Year");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel4.add(jLabel7, gridBagConstraints);

        jLabel8.setText("Vehicle Model");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel4.add(jLabel8, gridBagConstraints);

        claimFrameButton.setLabel("Find Claim");
        claimFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claimFrameButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(claimFrameButton, gridBagConstraints);

        customerNameBox.setText("Lizeth");
        customerNameBox.setPreferredSize(new java.awt.Dimension(65, 27));
        customerNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel4.add(customerNameBox, gridBagConstraints);

        vehicleYearBox.setText("2011");
        vehicleYearBox.setMinimumSize(new java.awt.Dimension(1100, 27));
        vehicleYearBox.setPreferredSize(new java.awt.Dimension(65, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        jPanel4.add(vehicleYearBox, gridBagConstraints);

        vehicleMakeBox.setText("honda");
        vehicleMakeBox.setPreferredSize(new java.awt.Dimension(65, 27));
        vehicleMakeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleMakeBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel4.add(vehicleMakeBox, gridBagConstraints);

        vehicleModelBox.setText("accord");
        vehicleModelBox.setPreferredSize(new java.awt.Dimension(65, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        jPanel4.add(vehicleModelBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jPanel4, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Customer Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel3.add(jLabel2, gridBagConstraints);

        editVehicleButton.setActionCommand("Find Customer");
        editVehicleButton.setLabel("Find Customer");
        editVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editVehicleButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(editVehicleButton, gridBagConstraints);

        customerNameBox2.setText("Lizeth");
        customerNameBox2.setPreferredSize(new java.awt.Dimension(65, 27));
        customerNameBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameBox2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel3.add(customerNameBox2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jPanel3, gridBagConstraints);

        button2.setLabel("Show Vehicles");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        getContentPane().add(button2, gridBagConstraints);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        windowMenu.setText("Window");

        customerFrameMenuItem.setText("Customer View");
        customerFrameMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerFrameMenuItemActionPerformed(evt);
            }
        });
        windowMenu.add(customerFrameMenuItem);

        jMenuItem2.setText("jMenuItem2");
        windowMenu.add(jMenuItem2);

        jMenuBar1.add(windowMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editVehicleButtonActionPerformed
        try{
            Object[] result = customerDao.findByName(customerNameBox2.getText());
            customerFrame.setCustomer((Customer) result[0]);
            customerFrame.setVisible(true);
            customerFrame.pack();
        } catch (SQLException ex) {
            Logger.getLogger(MasterFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editVehicleButtonActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed

        CarSearchFrame vehicles = new CarSearchFrame();
        vehicles.setTitle("Getting There");
        vehicles.setVisible(true);    }//GEN-LAST:event_button2ActionPerformed

    private void customerNameBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameBox2ActionPerformed

    private void claimFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claimFrameButtonActionPerformed
        try{
            Object[] result = claimDao.findClaim(customerNameBox2.getText(), vehicleYearBox.getText(), vehicleMakeBox.getText(), vehicleModelBox.getText());
            claimFrame.setContact((Contact) result[3]);
            claimFrame.setClaim((Claim) result[0]);
            claimFrame.setVehicle((Vehicle) result[1]);
            claimFrame.setVisible(true);
            claimFrame.pack();
        } catch (SQLException ex) {
            Logger.getLogger(MasterFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_claimFrameButtonActionPerformed

    private void customerNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameBoxActionPerformed

    private void vehicleMakeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleMakeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleMakeBoxActionPerformed

    private void customerFrameMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerFrameMenuItemActionPerformed
        customerFrame.setVisible(true);
        customerFrame.pack();
    }//GEN-LAST:event_customerFrameMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterFrame().setVisible(true);
            }
        });
    }

    private final CustomerFrame customerFrame;
    private final ClaimFrame claimFrame;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button2;
    private java.awt.Button claimFrameButton;
    private javax.swing.JMenuItem customerFrameMenuItem;
    private javax.swing.JTextField customerNameBox;
    private javax.swing.JTextField customerNameBox2;
    private java.awt.Button editVehicleButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField vehicleMakeBox;
    private javax.swing.JTextField vehicleModelBox;
    private javax.swing.JTextField vehicleYearBox;
    private javax.swing.JMenu windowMenu;
    // End of variables declaration//GEN-END:variables
}
