/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DBConnector;

import com.automo.ApplicationContext;
import com.automo.ClaimFrame;
import com.automo.CustomerFrame;
import com.automo.Event;
import com.automo.dao.ClaimDao;
import com.automo.dao.CustomerDao;
import com.automo.dao.OrderDao;
import com.automo.entity.Claim;
import com.automo.entity.Contact;
import com.automo.entity.Vehicle;

import javax.swing.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 */
public class MasterFrame extends javax.swing.JFrame {

    ClaimDao claimDao;
    ApplicationContext ctx = ApplicationContext.getInstance();
    CustomerDao customerDao;
    OrderDao orderDao;

    /**
     * Creates new form MasterFrame
     */
    private MasterFrame() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
//            UIManager.setLookAndFeel( "com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MasterFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();

        claimDao = new ClaimDao();
        customerDao = new CustomerDao();
        claimFrame = new ClaimFrame();
        customerFrame = new CustomerFrame();
        orderTableModel = new OrderTableModel();
        orderDao = new OrderDao();
        setup();
        setTitle("MasterFrame");
        pack();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ordersPanel = new javax.swing.JPanel();
        ordersLabel = new javax.swing.JLabel();
        ordersScrollPane = new javax.swing.JScrollPane();
        ordersTable = new javax.swing.JTable();
        newOrderButton = new javax.swing.JButton();
        findOrderPanel = new javax.swing.JPanel();
        findOrderLabel = new javax.swing.JLabel();
        findOrderInputPanel = new javax.swing.JPanel();
        vehicleMakeLabel = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        vehicleYearLabel = new javax.swing.JLabel();
        vehicleModelLabel = new javax.swing.JLabel();
        customerNameBox = new javax.swing.JTextField();
        vehicleYearBox = new javax.swing.JTextField();
        vehicleMakeBox = new javax.swing.JTextField();
        vehicleModelBox = new javax.swing.JTextField();
        findClaimButton = new java.awt.Button();
        findVehicleButton = new java.awt.Button();
        findCustomerButton = new java.awt.Button();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        windowMenu = new javax.swing.JMenu();
        customerFrameMenuItem = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        ordersPanel.setLayout(new java.awt.GridBagLayout());

        ordersLabel.setText("Orders");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        ordersPanel.add(ordersLabel, gridBagConstraints);

        ordersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ordersScrollPane.setViewportView(ordersTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        ordersPanel.add(ordersScrollPane, gridBagConstraints);

        getContentPane().add(ordersPanel, new java.awt.GridBagConstraints());

        newOrderButton.setText("New Order");
        newOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newOrderButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(newOrderButton, gridBagConstraints);

        findOrderPanel.setLayout(new java.awt.GridBagLayout());

        findOrderLabel.setText("Find Order");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        findOrderPanel.add(findOrderLabel, gridBagConstraints);

        findOrderInputPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        findOrderInputPanel.setLayout(new java.awt.GridBagLayout());

        vehicleMakeLabel.setText("Vehicle Make");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        findOrderInputPanel.add(vehicleMakeLabel, gridBagConstraints);

        customerNameLabel.setText("Customer Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        findOrderInputPanel.add(customerNameLabel, gridBagConstraints);

        vehicleYearLabel.setText("Vehicle Year");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        findOrderInputPanel.add(vehicleYearLabel, gridBagConstraints);

        vehicleModelLabel.setText("Vehicle Model");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        findOrderInputPanel.add(vehicleModelLabel, gridBagConstraints);

        customerNameBox.setText("Lizeth");
        customerNameBox.setPreferredSize(new java.awt.Dimension(80, 27));
        customerNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        findOrderInputPanel.add(customerNameBox, gridBagConstraints);

        vehicleYearBox.setText("2011");
        vehicleYearBox.setMinimumSize(new java.awt.Dimension(1100, 27));
        vehicleYearBox.setPreferredSize(new java.awt.Dimension(80, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        findOrderInputPanel.add(vehicleYearBox, gridBagConstraints);

        vehicleMakeBox.setText("honda");
        vehicleMakeBox.setPreferredSize(new java.awt.Dimension(80, 27));
        vehicleMakeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleMakeBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        findOrderInputPanel.add(vehicleMakeBox, gridBagConstraints);

        vehicleModelBox.setText("accord");
        vehicleModelBox.setPreferredSize(new java.awt.Dimension(80, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        findOrderInputPanel.add(vehicleModelBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        findOrderPanel.add(findOrderInputPanel, gridBagConstraints);

        findClaimButton.setLabel("Find Claim");
        findClaimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findClaimButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        findOrderPanel.add(findClaimButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        getContentPane().add(findOrderPanel, gridBagConstraints);

        findVehicleButton.setLabel("Find Vehicle");
        findVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findVehicleButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        getContentPane().add(findVehicleButton, gridBagConstraints);

        findCustomerButton.setLabel("Find Customer");
        findCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findCustomerButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        getContentPane().add(findCustomerButton, gridBagConstraints);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        windowMenu.setText("Window");

        customerFrameMenuItem.setText("Customer View");
        customerFrameMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerFrameMenuItemActionPerformed(evt);
            }
        });
        windowMenu.add(customerFrameMenuItem);

        jMenuItem2.setText("jMenuItem2");
        windowMenu.add(jMenuItem2);

        jMenuBar1.add(windowMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setup(){
        orderTableModel.getItems().addAll(orderDao.findAll());
        ordersTable.setModel(orderTableModel);
    }

    private void findCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findCustomerButtonActionPerformed
        ctx.getEventBus().post(new Event.ShowFrameEvent(ctx.getCustomerPicker()));
    }//GEN-LAST:event_findCustomerButtonActionPerformed

    private void findVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findVehicleButtonActionPerformed

        CarSearchFrame vehicles = new CarSearchFrame();
        vehicles.setTitle("Getting There");
        vehicles.setVisible(true);
    }//GEN-LAST:event_findVehicleButtonActionPerformed

    private void findClaimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findClaimButtonActionPerformed
        try {
            Object[] result = claimDao.findClaim(customerNameBox.getText(), vehicleYearBox.getText(), vehicleMakeBox.getText(), vehicleModelBox.getText());
            claimFrame.setContact((Contact) result[3]);
            claimFrame.setClaim((Claim) result[0]);
            claimFrame.setVehicle((Vehicle) result[1]);
            claimFrame.setVisible(true);
            claimFrame.pack();
        } catch (SQLException ex) {
            Logger.getLogger(MasterFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_findClaimButtonActionPerformed

    private void customerNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameBoxActionPerformed

    private void vehicleMakeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleMakeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleMakeBoxActionPerformed

    private void customerFrameMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerFrameMenuItemActionPerformed
        customerFrame.setVisible(true);
        customerFrame.pack();
    }//GEN-LAST:event_customerFrameMenuItemActionPerformed

    private void newOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newOrderButtonActionPerformed
        // TODO add your handling code here:
        ApplicationContext ctx  = ApplicationContext.getInstance();
        ctx.getEventBus().post(new Event.ShowFrameEvent(ctx.getSingleOrderFrame()));
    }//GEN-LAST:event_newOrderButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterFrame().setVisible(true);
            }
        });
    }

    private final CustomerFrame customerFrame;
    private final ClaimFrame claimFrame;
    private final OrderTableModel orderTableModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem customerFrameMenuItem;
    private javax.swing.JTextField customerNameBox;
    private javax.swing.JLabel customerNameLabel;
    private java.awt.Button findClaimButton;
    private java.awt.Button findCustomerButton;
    private javax.swing.JPanel findOrderInputPanel;
    private javax.swing.JLabel findOrderLabel;
    private javax.swing.JPanel findOrderPanel;
    private java.awt.Button findVehicleButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton newOrderButton;
    private javax.swing.JLabel ordersLabel;
    private javax.swing.JPanel ordersPanel;
    private javax.swing.JScrollPane ordersScrollPane;
    private javax.swing.JTable ordersTable;
    private javax.swing.JTextField vehicleMakeBox;
    private javax.swing.JLabel vehicleMakeLabel;
    private javax.swing.JTextField vehicleModelBox;
    private javax.swing.JLabel vehicleModelLabel;
    private javax.swing.JTextField vehicleYearBox;
    private javax.swing.JLabel vehicleYearLabel;
    private javax.swing.JMenu windowMenu;
    // End of variables declaration//GEN-END:variables
}
